import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import dynamic from 'next/dynamic';

const TopSection = dynamic(() => import('../components/TopSection'), {
  loading: () => <p>...</p>,
});

const MidSection = dynamic(() => import('../components/MidSection'), {
  loading: () => <p>...</p>,
});

const BottomSection = dynamic(() => import('../components/BottomSection'), {
  loading: () => <p>...</p>,
});

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <TopSection />
      <MidSection />
      <BottomSection />
    </div>
  );
}
